package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /builddir/build/BUILD/java-1.8.0-openjdk-1.8.0.232.b09-0.fc29.x86_64/openjdk/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, October 16, 2019 2:34:11 PM UTC
*/

public interface TAG_POLICIES
{

  /**
       * A profile component containing the sequence of QoS policies exported
       * with the object reference by an object adapter.
       */
  public static final int value = (int)(2L);
}
