package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /builddir/build/BUILD/java-1.8.0-openjdk-1.8.0.232.b09-0.fc29.x86_64/openjdk/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, October 16, 2019 2:34:11 PM UTC
*/

public interface THREAD_POLICY_ID
{

  /**
  	 * The value representing THREAD_POLICY_ID.
  	 */
  public static final int value = (int)(16L);
}
